### ISSUE TITLE
java.lang.NoClassDefFoundError is observed when building a project 

### ISSUE THREAD

**Issue by anuruddhal** [ballerina-platform/openapi-tools#921]
**Description:**
Following error observed when building a project using Ballerina 1.2.25 release. The same code works in Ballerina 1.2.16.
```
[2022-03-04 07:17:46,426] SEVERE {b7a.log.crash} - com/fasterxml/jackson/datatype/jsr310/JavaTimeModule
java.lang.NoClassDefFoundError: com/fasterxml/jackson/datatype/jsr310/JavaTimeModule
	at io.swagger.v3.core.util.Json.mapper(Json.java:13)
	at io.swagger.v3.parser.util.OpenAPIDeserializer.getExtensions(OpenAPIDeserializer.java:234)
	at io.swagger.v3.parser.util.OpenAPIDeserializer.getOperation(OpenAPIDeserializer.java:2829)
	at io.swagger.v3.parser.util.OpenAPIDeserializer.getPathItem(OpenAPIDeserializer.java:657)
	at io.swagger.v3.parser.util.OpenAPIDeserializer.getPaths(OpenAPIDeserializer.java:548)
	at io.swagger.v3.parser.util.OpenAPIDeserializer.parseRoot(OpenAPIDeserializer.java:160)
	at io.swagger.v3.parser.util.OpenAPIDeserializer.deserialize(OpenAPIDeserializer.java:119)
	at io.swagger.v3.parser.OpenAPIV3Parser.readWithInfo(OpenAPIV3Parser.java:118)
	at io.swagger.v3.parser.OpenAPIV3Parser.readWithInfo(OpenAPIV3Parser.java:156)
	at io.swagger.v3.parser.OpenAPIV3Parser.readLocation(OpenAPIV3Parser.java:58)
	at io.swagger.v3.parser.OpenAPIV3Parser.read(OpenAPIV3Parser.java:104)
	at io.swagger.v3.parser.OpenAPIV3Parser.read(OpenAPIV3Parser.java:92)
	at org.ballerinalang.openapi.validator.ValidatorUtil.parseOpenAPIFile(ValidatorUtil.java:70)
	at org.ballerinalang.openapi.validator.OpenAPIValidatorPlugin.process(OpenAPIValidatorPlugin.java:191)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.lambda$visit$11(CompilerPluginRunner.java:183)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.notifyProcessors(CompilerPluginRunner.java:283)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.visit(CompilerPluginRunner.java:183)
	at org.wso2.ballerinalang.compiler.tree.BLangService.accept(BLangService.java:126)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.lambda$visit$3(CompilerPluginRunner.java:138)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.visit(CompilerPluginRunner.java:138)
	at org.wso2.ballerinalang.compiler.tree.BLangPackage.accept(BLangPackage.java:161)
	at org.wso2.ballerinalang.compiler.semantics.analyzer.CompilerPluginRunner.runPlugins(CompilerPluginRunner.java:126)
	at org.wso2.ballerinalang.compiler.CompilerDriver.annotationProcess(CompilerDriver.java:294)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compile(CompilerDriver.java:252)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackageSymbol(CompilerDriver.java:214)
	at org.wso2.ballerinalang.compiler.CompilerDriver.compilePackage(CompilerDriver.java:131)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackages(Compiler.java:166)
	at org.wso2.ballerinalang.compiler.Compiler.compilePackage(Compiler.java:174)
	at org.wso2.ballerinalang.compiler.Compiler.compile(Compiler.java:91)
	at org.wso2.ballerinalang.compiler.Compiler.build(Compiler.java:99)
	at org.ballerinalang.packerina.task.CompileTask.execute(CompileTask.java:61)
	at org.ballerinalang.packerina.TaskExecutor.executeTasks(TaskExecutor.java:38)
	at org.ballerinalang.packerina.cmd.BuildCommand.execute(BuildCommand.java:436)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.ballerinalang.tool.Main.main(Main.java:57)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.datatype.jsr310.JavaTimeModule
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 36 more
```

**Steps to reproduce:**

**Affected Versions:**
Ballerina 1.2.25

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**
